version: '3.8'

services:
  db:
      image: postgres:15-alpine
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASS}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

  backend:
    image: venuradenethpriya/myproject-backend:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  
  frontend:
    build:
      context: ./FE
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  pgdata:
        

