import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica',
        backgroundColor: '#f9fafb',
    },
    header: {
        fontSize: 26,
        marginBottom: 20,
        textAlign: 'center',
        color: '#1e40af',
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    section: {
        backgroundColor: '#ffffff',
        border: '1pt solid #d1d5db',
        borderRadius: 6,
        padding: 20,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottom: '1pt solid #e5e7eb',
    },
    lastRow: {
        borderBottom: 0,
    },
    label: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#374151',
        width: '35%',
    },
    value: {
        fontSize: 12,
        color: '#111827',
        width: '60%',
        textAlign: 'right',
    },
    footer: {
        marginTop: 30,
        fontSize: 10,
        textAlign: 'center',
        color: '#9ca3af',
    }
});

const OtherDetailsTemplate = ({ productData }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>Other Product Details</Text>

            <View style={styles.section}>
                <View style={styles.row}>
                    <Text style={styles.label}>Product Name</Text>
                    <Text style={styles.value}>{productData.name}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Category</Text>
                    <Text style={styles.value}>{productData.category}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Base Price</Text>
                    <Text style={styles.value}>Rs. {productData.base_price}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Voltage</Text>
                    <Text style={styles.value}>{productData.voltage}V</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Brand Name</Text>
                    <Text style={styles.value}>{productData.Specifications}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Report Generated At:</Text>
                    <Text style={styles.value}>{new Date().toLocaleString()}</Text>
                </View>
            </View>

            <Text style={styles.footer}>Generated by RIMS</Text>
        </Page>
    </Document>
);

export default OtherDetailsTemplate;
